### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [pepperjam/gtm-integration#2]
Thanks for submitting a template to the gallery, there were a few issues in your template that needs to be resolved ahead of approving the template for the gallery.

1) The documentation URL mentioned in the manifest file [https://www.pepperjam.com/documentation](https://www.pepperjam.com/documentation) shows error "We are sorry the page you are looking for can't be found."
2) encodeUriComponent should be used on user provided values that are then used as parameters in your url. These methods take in a single text arguement and return a URI Encoded string. You should use this method on "aID", "programID", "urlSRC" when generating the url
const url = 'https://container.pepperjam.com/' + aID + '.js'; and 
const url = "https://t.pepperjamnetwork.com/track?" + "INT=DYNAMIC&PROGRAM_ID=" + programID + "&" + urlSRC.join("&");

**Comment by haeder-pepperjam** [comment]
Hi there! We only realized you left us comments last week. We have updated the repository to address your feedback. Please let us know what you think. 
Thanks, Heather

**Comment by haeder-pepperjam** [comment]
@praveena-pappu Any thoughts on our response? Thanks so much for your consideration!

**Comment by haeder-pepperjam** [comment]
@praveena-pappu Hi! What do you think of our responses to your feedback?

**Comment by haeder-pepperjam** [comment]
@praveena-pappu Hi! Me again, just wanted to check in. We are eager to move forward. Thanks so much, Heather

**Comment by praveena-pappu** [comment]
Hello as requested earlier, we have reviewed the tag. Please refer to live version https://tagmanager.google.com/gallery/#/owners/pepperjam/templates/gtm-integration
